stages:
  - test

robot_tests:
  stage: test
  image: python:3.11
  before_script:
    - pip install robotframework
  script:
    - robot --outputdir results tests/ci_test.robot
  artifacts:
    when: always
    paths:
      - results/
    expire_in: 7 days
  only:
    - master