stages:
  - test

robot_tests:
  stage: test
  image: python:3.11
  before_script:
    - pip install robotframework
  script:
    - echo "Pipeline GitLab CI operationnel"
    - python -m robot --version || true
  only:
    - master